Rar executable detection needs to be after mime type detection

diff --git a/unrarall b/unrarall
--- a/unrarall
+++ b/unrarall
@@ -755,35 +755,37 @@ if [ "${DIR}" == "." ]; then
 fi
 
 #If No user specified binary, cycle through array and try and find a binary that can be used
-if [ -z "${UNRARALL_BIN}" ]; then
-  for (( index=0; index < ${#UNRAR_BINARIES[@]}; index++)); do
-    #Check for binary
-    [ $VERBOSE -eq 1 ] && message nnl "Looking for ${UNRAR_BINARIES[$index]}..."
-    if type -P ${UNRAR_BINARIES[$index]} 2>&1 > /dev/null ; then
-      #Binary found
-      UNRARALL_BIN="${UNRAR_BINARIES[$index]}"
-      [ $VERBOSE -eq 1 ] && message ok "found"
-      break;
-    else
-      [ $VERBOSE -eq 1 ] && message error "not found"
-    fi
+function detect_unrar_bin() {
+  if [ -z "${UNRARALL_BIN}" ]; then
+    for (( index=0; index < ${#UNRAR_BINARIES[@]}; index++)); do
+      #Check for binary
+      [ $VERBOSE -eq 1 ] && message nnl "Looking for ${UNRAR_BINARIES[$index]}..."
+      if type -P ${UNRAR_BINARIES[$index]} 2>&1 > /dev/null ; then
+        #Binary found
+        UNRARALL_BIN="${UNRAR_BINARIES[$index]}"
+        [ $VERBOSE -eq 1 ] && message ok "found"
+        break;
+      else
+        [ $VERBOSE -eq 1 ] && message error "not found"
+      fi
 
-    #check if end of list
-    if [ $index -eq $(( ${#UNRAR_BINARIES[@]} -1)) ]; then
-      message error "Failed to find binary to perform rar extraction. The following binaries were looked for ${UNRAR_BINARIES[*]}"
+      #check if end of list
+      if [ $index -eq $(( ${#UNRAR_BINARIES[@]} -1)) ]; then
+        message error "Failed to find binary to perform rar extraction. The following binaries were looked for ${UNRAR_BINARIES[*]}"
+        exit 1;
+      fi
+    done
+  else
+    #check the manually specified binary exists
+    if ! type -P ${UNRARALL_BIN} 2>&1 > /dev/null ; then
+      message error "The manually specified binary ${UNRARALL_BIN} cannot be found"
       exit 1;
     fi
-  done
-else
-  #check the manually specified binary exists
-  if ! type -P ${UNRARALL_BIN} 2>&1 > /dev/null ; then
-    message error "The manually specified binary ${UNRARALL_BIN} cannot be found"
-    exit 1;
   fi
-fi
 
-#Inform the user about the binary chosen
-[ $VERBOSE -eq 1 ] && message info "Using \"${UNRARALL_BIN}\" to extract rar files" ;
+  #Inform the user about the binary chosen
+  [ $VERBOSE -eq 1 ] && message info "Using \"${UNRARALL_BIN}\" to extract rar files" ;
+}
 
 # Check $DIR exists and is a directory
 if [ -d "$DIR" ]; then
@@ -829,7 +831,7 @@ for file in $(find_wrapper "$DIR" -depth -iregex '.*\.(rar|001|zip|7z|7z\.001)$'
   elif [[ "$mime_type" =~ $MATCH7ZMIME ]]; then
     UNRARALL_BIN="7z"
   elif [[ "$mime_type" =~ $MATCHRARMIME ]]; then
-    UNRARALL_BIN=""  # left empty to use UNRAR_BINARIES
+    detect_unrar_bin
   else
     message error "Skipping file \"${file}\" because it does not appear to be a valid rar file."
     # Treat this as a failure so we exit with a non zero exit code
