Extractor for rar files is now determined beforehand and then cached, otherwise it will be overwritten by a different extractor later and will not be detected again

diff --git a/unrarall b/unrarall
--- a/unrarall
+++ b/unrarall
@@ -33,6 +33,7 @@ declare -ix ALLOW_FAILURES=0
 declare -x UNRAR_METHOD="x"
 declare -x CKSFV_FLAGS="-q -g"
 declare -x UNRARALL_BIN="" #Leave empty to let unrarall to loop through UNRAR_BINARIES, setting this will disable searching through UNRAR_BINARIES
+declare -x UNRARALL_DETECTED_RAR_BIN=""
 declare -x UNRAR_BINARIES=(unrar rar 7z) #Array of binaries to try and use, the order here is the order of precedence
 declare -x UNRARALL_PID="$$"
 declare -x UNRARALL_EXECUTABLE_NAME=$(basename $0;)
@@ -762,37 +763,36 @@ if [ "${DIR}" == "." ]; then
 fi
 
 #If No user specified binary, cycle through array and try and find a binary that can be used
-function detect_unrar_bin() {
-  if [ -z "${UNRARALL_BIN}" ]; then
-    for (( index=0; index < ${#UNRAR_BINARIES[@]}; index++)); do
-      #Check for binary
-      [ $VERBOSE -eq 1 ] && message nnl "Looking for ${UNRAR_BINARIES[$index]}..."
-      if type -P ${UNRAR_BINARIES[$index]} 2>&1 > /dev/null ; then
-        #Binary found
-        UNRARALL_BIN="${UNRAR_BINARIES[$index]}"
-        [ $VERBOSE -eq 1 ] && message ok "found"
-        break;
-      else
-        [ $VERBOSE -eq 1 ] && message error "not found"
-      fi
-
-      #check if end of list
-      if [ $index -eq $(( ${#UNRAR_BINARIES[@]} -1)) ]; then
-        message error "Failed to find binary to perform rar extraction. The following binaries were looked for ${UNRAR_BINARIES[*]}"
-        exit 1;
-      fi
-    done
+if [ -z "${UNRARALL_BIN}" ]; then
+for (( index=0; index < ${#UNRAR_BINARIES[@]}; index++)); do
+  #Check for binary
+  [ $VERBOSE -eq 1 ] && message nnl "Looking for ${UNRAR_BINARIES[$index]}..."
+  if type -P ${UNRAR_BINARIES[$index]} 2>&1 > /dev/null ; then
+    #Binary found
+    UNRARALL_DETECTED_RAR_BIN="${UNRAR_BINARIES[$index]}"
+    [ $VERBOSE -eq 1 ] && message ok "found"
+    break;
   else
-    #check the manually specified binary exists
-    if ! type -P ${UNRARALL_BIN} 2>&1 > /dev/null ; then
-      message error "The manually specified binary ${UNRARALL_BIN} cannot be found"
-      exit 1;
-    fi
+    [ $VERBOSE -eq 1 ] && message error "not found"
   fi
 
-  #Inform the user about the binary chosen
-  [ $VERBOSE -eq 1 ] && message info "Using \"${UNRARALL_BIN}\" to extract rar files" ;
-}
+  #check if end of list
+  if [ $index -eq $(( ${#UNRAR_BINARIES[@]} -1)) ]; then
+    message error "Failed to find binary to perform rar extraction. The following binaries were looked for ${UNRAR_BINARIES[*]}"
+    exit 1;
+  fi
+done
+else
+#check the manually specified binary exists
+if ! type -P ${UNRARALL_BIN} 2>&1 > /dev/null ; then
+  message error "The manually specified binary ${UNRARALL_BIN} cannot be found"
+  exit 1;
+fi
+fi
+
+#Inform the user about the binary chosen
+[ $VERBOSE -eq 1 ] && message info "Using \"${UNRARALL_DETECTED_RAR_BIN}\" to extract rar files" ;
+
 
 # Check $DIR exists and is a directory
 if [ -d "$DIR" ]; then
@@ -838,7 +838,7 @@ for file in $(find_wrapper "$DIR" -depth -iregex '.*\.(rar|001|zip|7z|7z\.001)$'
   elif [[ "$mime_type" =~ $MATCH7ZMIME ]]; then
     UNRARALL_BIN="7z"
   elif [[ "$mime_type" =~ $MATCHRARMIME ]]; then
-    detect_unrar_bin
+    UNRARALL_BIN=$UNRARALL_DETECTED_RAR_BIN
   else
     message error "Skipping file \"${file}\" because it does not appear to be a valid rar file."
     # Treat this as a failure so we exit with a non zero exit code
